### ISSUE TITLE
http://lidordf.aksw.org/ returns 503 Error

### ISSUE THREAD

**Issue by b0rt** [AKSW/lido2rdf#1]
Hi there,

 i am interested in a LIDO Rdf represantion, and was glad to have found your project.
 I found that http://lidordf.aksw.org/ returns an error code,
 
 could you maybe include a guide how to use this repository to generate a rdf file?
 
 Thank you kindly,
 Stephan

**Comment by b0rt** [comment]
ah, i think i may have misunderstood this repository.. i was researching LIDO (Lightweight Information for Describing Objects) [project link](https://cidoc.mini.icom.museum/working-groups/lido/lido-overview/about-lido/what-is-lido/) but this is a LiDo Terminological and Bibliographical Database (LiDo TBD) to RDF project

**Comment by aottr** [comment]
Indeed. The main purpose of this project was to convert an existing Linguistic Documentation RDB into RDF. The public files are only for reference :)
